GaraceConcept/ViewModels/Images/AddImagesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GarageConcept.ViewModels.Images
{
    public class AddImagesViewModel
    {
        public int Id { get; set; }
    }
}

GaraceConcept/ViewModels/Images/ImageViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GarageConcept.ViewModels.Images
{
    public class ImageViewModel
    {
        public string DeleteType { get; set; }
        public string Name { get; set; }
        public int Size { get; set; }
        public string Url { get; set; }
        public string ThumbnailUrl { get; set; }
        public string DeleteUrl { get; set; }
        public int Id { get; set; }
        public DateTime CreatedAt { get; set; }
    }
}

GaraceConcept/Controllers/ImagesController.cs
using GarageConcept.Data.Context;
using GarageConcept.ViewModels.Images;
using GarageConcept.ViewModels.Orders;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace GarageConcept.Controllers
{

    public class ImagesController : Controller
    {
        
        private const int ThumbSize = 160;

        [Authorize(Roles = "ADMIN")]
        public ActionResult Add(int id)
        {
            using (var db = new GarageConceptContext())
            {
                var model = db.Orders.Where(o => o.Id == id)
                    .Select(o => new AddImagesViewModel
                    {
                        Id = o.Id,
                    })
                    .FirstOrDefault();
                return View(model);

            }
        }

        public async Task<ActionResult> GetFile(int id, bool thumbnail = false)
        {
            using (var db = new GarageConceptContext())
            {
                var file = await db.OrderImages.FindAsync(id);
                return thumbnail ? Thumb(file.Data, "image/png") : File(file.Data, "image/png");
            }
        }

        [Authorize(Roles = "ADMIN")]
        [HttpPost]
        public async Task<ActionResult> DeleteFile(int id)
        {
            using (var db = new GarageConceptContext())
            {
                var file = await db.OrderImages.FindAsync(id);
                db.OrderImages.Remove(file);
                await db.SaveChangesAsync();
                return Json($"Imagem [{file.FileName}] excluída");
            }
        }

        [Authorize(Roles = "ADMIN")]
        [HttpGet]
        public async Task<ActionResult> Upload(string[] names)
        {
            using (var db = new GarageConceptContext())
            {
                var files = await db.OrderImages
                    .Where(i => names.Contains(i.FileName))
                    .Select(file => new ImageViewModel
                    {
                        Id = file.Id,
                        DeleteType = "POST",
                        Name = file.FileName,
                        Size = file.DataLength
                    }).ToListAsync();

                foreach (var file in files)
                {
                    file.Url = Url.Action("GetFile", "Images", new { file.Id });
                    file.ThumbnailUrl = Url.Action("GetFile", "Images", new { file.Id, thumbnail = true });
                    file.DeleteUrl = Url.Action("DeleteFile", "Images", new { file.Id });
                }

                return Json(new
                {
                    files
                }, JsonRequestBehavior.AllowGet);
            }
        }

        [Authorize(Roles = "ADMIN")]
        [HttpPost]
        public async Task<ActionResult> Upload(int id)
        {
            var files = Request.Files
                .Cast<string>()
                .Select(k => Request.Files[k])
                .ToArray();

            using (var db = new GarageConceptContext())
            {
                var order = await db.Orders.FindAsync(id);
                foreach (var file in files)
                    order.AddImage(file.FileName, file.ToByteArray());
                await db.SaveChangesAsync();
            }
            
            var names = files.Select(f => f.FileName);
            return await Upload(names.ToArray());
        }

        private ActionResult Thumb(byte[] data, string contentType)
        {
            if (contentType.StartsWith("image"))
            {
                using (var ms = new MemoryStream(data))
                using (var img = Image.FromStream(ms))
                {
                    var thumbHeight = (int)(img.Height * (ThumbSize / (double)img.Width));
                    var thumb = data.FixImageSize(ThumbSize, thumbHeight);
                    return File(thumb, contentType);
                }
            }

            return Redirect($"https://placehold.it/{ThumbSize}?text={Url.Encode("png")}");
        }

    }
}

GaraceConcept/Controllers/OrdersController.cs
using GarageConcept.Data.Context;
using GarageConcept.Helpers;
using GarageConcept.Models;
using GarageConcept.ViewModels.Orders;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Data.Entity;
using GarageConcept.Services;
using System.Web;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;

namespace GarageConcept.Controllers
{
    [Authorize]
    public class OrdersController : BaseController
    {

        private const int ThumbSize = 160;
        
        public ActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "ADMIN")]
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "ADMIN")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateOrderViewModel model)
        {
            if (ModelState.IsValid)
            {
                using (var db = new GarageConceptContext())
                {
                    var vehicle = await db.Vehicles.FirstOrDefaultAsync(v => v.PlateNumber == model.Plate);
                    if (vehicle == null)
                        vehicle = db.Vehicles.Add(new Vehicle(model.Plate));
                    vehicle.ChassisNumber = model.Chassis;
                    vehicle.Model = model.VehicleModel;
                    var owner = await db.Users.FirstOrDefaultAsync(u => u.Cpf == model.OwnerCpf) ?? new User(model.OwnerCpf);
                    owner.Name = model.OwnerName;
                    vehicle.Owner = owner;

                    var os = new Order(vehicle);
                    os.Description = model.Description;
                    os.AddToHistory("OS criada");
                    db.Orders.Add(os);

                    await db.SaveChangesAsync();
                }
                return RedirectToAction("Index");
            }
            return View();
        }

        [Authorize(Roles = "ADMIN")]
        [HttpGet]
        public async Task<ActionResult> Edit(int id)
        {
            using (var db = new GarageConceptContext())
            {
                var model = await db.Orders.Where(o => o.Id == id)
                    .Select(o => new EditOrderViewModel
                    {
                        Id = o.Id,
                        Chassis = o.Vehicle.ChassisNumber,
                        OwnerCpf = o.OwnerAtOrderDate.Cpf,
                        OwnerName = o.OwnerAtOrderDate.Name,
                        VehicleModel = o.Vehicle.Model,
                        Description = o.Description
                    })
                    .FirstOrDefaultAsync();
                return View(model);
            }
        }

        [Authorize(Roles = "ADMIN")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(EditOrderViewModel model)
        {
            if (ModelState.IsValid)
            {
                using (var db = new GarageConceptContext())
                {
                    var order = await db.Orders.Include(o => o.Vehicle.Owner).Include(o => o.OwnerAtOrderDate).FirstOrDefaultAsync(o => o.Id == model.Id);
                    order.Vehicle.ChassisNumber = model.Chassis;
                    order.Vehicle.Model = model.VehicleModel;
                    order.Description = model.Description;
                    if (order.OwnerAtOrderDate.Cpf != model.OwnerCpf)
                    {
                        var owner = await db.Users.FirstOrDefaultAsync(u => u.Cpf == model.OwnerCpf) ?? new User(model.OwnerCpf);
                        owner.Name = model.OwnerName;
                        order.OwnerAtOrderDate = owner;
                        order.AddToHistory($"OS transferida para {owner.Name}.");
                        if (model.UpdateVehicleOwner)
                        {
                            order.Vehicle.Owner = owner;
                            order.AddToHistory($"{owner.Name} é o novo proprietário do veículo.");
                        }
                    }
                    await db.SaveChangesAsync();
                }
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public async Task<ActionResult> Details(int id)
        {
            using (var db = new GarageConceptContext())
            {
                var q = db.Orders.Where(o => o.Id == id)
                    .Select(o => new OrderDetailsViewModel
                    {
                        Id = o.Id,
                        PlateNumber = o.Vehicle.PlateNumber,
                        Chassis = o.Vehicle.ChassisNumber,
                        VehicleModel = o.Vehicle.Model,
                        OwnerCpf = o.OwnerAtOrderDate.Cpf,
                        OwnerId = o.OwnerAtOrderDate.Id,
                        OwnerName = o.OwnerAtOrderDate.Name,
                        OwnerPhone = o.OwnerAtOrderDate.PhoneNumber,
                        OwnerEmail = o.OwnerAtOrderDate.Email,
                        Description = o.Description,
                        Images = o.Images.Select(i => i.Id)
                    }).AsQueryable();

                bool isAdmin = AuthHelper.IsAdmin();
                if (!isAdmin)
                {
                    var userId = AuthHelper.GetLoggedUserId();
                    q = q.Where(o => o.OwnerId == userId);
                }

                var model = await q.FirstOrDefaultAsync();

                if (model == null)
                    return RedirectToAction("Index");

                model.IsAdmin = isAdmin;

                return View(model);
            }
        }
        
        public ActionResult InternalServerError()
        {
            AddToastrMessage(ToastrStatus.Info, "Ocorreu um erro, mas já estamos trabalhando em uma solução para o mesmo.");
            return View();
        }

        [Authorize(Roles = "ADMIN")]
        public async Task<ActionResult> GeneratePassword(int id)
        {
            using (var db = new GarageConceptContext())
            {
                var model = await db.Orders.Where(o => o.Id == id)
                .Select(o => new GeneratePasswordViewModel
                {
                    OrderId = o.Id,
                    PlateNumber = o.Vehicle.PlateNumber
                }).FirstOrDefaultAsync();

                model.Password = PasswordGeneratorService.CreatePassword(6);

                return View(model);
            }
        }

        [Authorize(Roles = "ADMIN")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> GeneratePassword(GeneratePasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                using (var db = new GarageConceptContext())
                {
                    var userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();

                    var owner = await db.Orders.Where(o => o.Id == model.OrderId).Select(o => o.OwnerAtOrderDate).FirstAsync();
                    IdentityResult passwordChangeResult;
                    if (string.IsNullOrWhiteSpace(owner.PasswordHash))
                    {
                        passwordChangeResult = await userManager.AddPasswordAsync(owner.Id, model.Password);
                    }
                    else
                    {
                        string resetToken = await userManager.GeneratePasswordResetTokenAsync(owner.Id);
                        passwordChangeResult = await userManager.ResetPasswordAsync(owner.Id, resetToken, model.Password);
                    }
                    if (passwordChangeResult.Succeeded)
                    {
                        AddToastrMessage(ToastrStatus.Success, "Senha atualizada com sucesso!");
                        return RedirectToAction("Index");
                    }
                    AddErrors(passwordChangeResult);
                }
            }
            return View(model);
        }

    }
}

GaraceConcept/Views/Images/Add.cshtml
@model GarageConcept.ViewModels.Images.AddImagesViewModel

@{
    ViewBag.Title = "AddImages";
}

<div class="row border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Adicionar Imagens</h2>
        <ol class="breadcrumb">
            <li>
                <a href="@Url.Action("Details", "Orders", new { id = Model.Id })">Detalhes OS @Model.Id.ToString()</a>
            </li>
            <li class="active">
                <strong>Adicionar Imagens</strong>
            </li>
        </ol>
    </div>
</div>


<!-- The file upload form used as target for the file upload widget-->
<form id="fileupload" method="POST" data-url="@Url.Action("Upload", new { id = Model.Id })" enctype="multipart/form-data">
    <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload-->
    <div class="row fileupload-buttonbar">
        <div class="col-lg-7">
            <!-- The fileinput-button span is used to style the file input field as button-->
            <span class="btn btn-success fileinput-button">
                <i class="fa fa-fw fa-plus"></i>
                <span>Adicionar Imagens</span>
                <input type="file" name="files[]" multiple="">
            </span>
            <button type="submit" class="btn btn-primary start">
                <i class="fa fa-fw fa-upload"></i>
                <span>Iniciar Upload</span>
            </button>
            <button type="reset" class="btn btn-warning cancel">
                <i class="fa fa-fw fa-times"></i>
                <span>Cancelar</span>
            </button>
            <!-- The global file processing state-->
            <span class="fileupload-process"></span>
        </div>
        <!-- The global progress state-->
        <div class="col-lg-5 fileupload-progress fade">
            <!-- The global progress bar-->
            <div role="progressbar" aria-valuemin="0" aria-valuemax="100" class="progress progress-striped active">
                <div style="width:0%;" class="progress-bar progress-bar-success"></div>
            </div>
            <!-- The extended global progress state-->
            <div class="progress-extended">&nbsp;</div>
        </div>
    </div>
    <!-- The table listing the files available for upload/download-->
    <table role="presentation" class="table table-striped">
        <tbody class="files"></tbody>
    </table>
</form>

<!-- The template to display files available for upload-->
<script id="template-upload" type="text/x-tmpl">
    {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td>
            <span class="preview"></span>
        </td>
        <td>
            <p class="name">{%=file.name%}</p>
            <strong class="error text-danger"></strong>
        </td>
        <td>
            <p class="size">Processing...</p>
            <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
        </td>
        <td>
            {% if (!i && !o.options.autoUpload) { %}
            <button class="btn btn-primary start" disabled>
                <em class="fa fa-fw fa-upload"></em>
                <span>Start</span>
            </button>
            {% } %}
            {% if (!i) { %}
            <button class="btn btn-warning cancel">
                <em class="fa fa-fw fa-times"></em>
                <span>Cancel</span>
            </button>
            {% } %}
        </td>
    </tr>
    {% } %}
</script>


<!-- The template to display files available for download-->
<script id="template-download" type="text/x-tmpl">
    {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        <td>
            <span class="preview">
                {% if (file.ThumbnailUrl) { %}
                <a href="{%=file.Url%}" title="{%=file.Name%}" download="{%=file.Name%}" data-gallery><img src="{%=file.ThumbnailUrl%}"></a>
                {% } %}
            </span>
        </td>
        <td>
            <p class="name">
                {% if (file.url) { %}
                <a href="{%=file.Url%}" title="{%=file.Name%}" download="{%=file.Name%}" {%=file.ThumbnailUrl?'data-gallery':''%}>{%=file.Name%}</a>
                {% } else { %}
                <span>{%=file.Name%}</span>
                {% } %}
            </p>
            {% if (file.error) { %}
            <div><span class="label label-danger">Error</span> {%=file.error%}</div>
            {% } %}
        </td>
        <td>
            <span class="size">{%=o.formatFileSize(file.size)%}</span>
        </td>
        <td>
            {% if (file.DeleteUrl) { %}
            <button class="btn btn-danger delete" data-type="{%=file.deleteType%}" data-url="{%=file.DeleteUrl%}" {% if (file.deletewithcredentials) { %} data-xhr-fields='{"withCredentials":true}' {% } %}>
                <em class="fa fa-fw fa-trash"></em>
                <span>Delete</span>
            </button>
            {% } else { %}
            <button class="btn btn-warning cancel">
                <em class="fa fa-fw fa-times"></em>
                <span>Cancel</span>
            </button>
            {% } %}
        </td>
    </tr>
    {% } %}
</script>

@section Styles {
    @Styles.Render("~/css/fileupload")
}
@section Scripts {
    @Scripts.Render("~/bundles/fileupload")
    @Scripts.Render("~/bundles/pages/images/add")
}