GaraceConcept/Models/Vehicle.cs
using GarageConcept.Models;
using System;
using System.Collections;
using System.Collections.Generic;

namespace GarageConcept.Models
{
    public class Vehicle: BaseEntity
    {

        public string PlateNumber { get; set; }

        public string ChassisNumber { get; set; }

        public string Model { get; set; }

        public virtual ICollection<Order> Orders { get; set; }

        public string OwnerId { get; set; }

        public virtual User Owner { get; set; }

        public Vehicle()
        {
            this.Orders = new HashSet<Order>();
        }

        public Vehicle(string plate): this()
        {
            this.PlateNumber = plate;
        }

    }
}

GaraceConcept/ViewModels/Vehicles/EditVehiclesViewModel.cs
using GarageConcept.Helpers.Attributes.DataAnnotations;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace GarageConcept.ViewModels.Vehicles
{
    public class EditVehiclesViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Por favor, preencha a placa!")]
        [DisplayName("Placa")]
        [RegexReplace(ReplaceThis = "-", WithThis = "")]
        public string PlateNumber { get; set; }

        [Required(ErrorMessage = "Por favor, preencha o chassi!")]
        [DisplayName("Chassi")]
        [MaxLength(17, ErrorMessage = "Um chassi deve ter no máximo {1} caracteres.")]
        public string Chassis { get; set; }

        [Required(ErrorMessage = "Por favor, preencha o model!")]
        [DisplayName("Modelo")]
        public string VehicleModel { get; set; }

        [Required(ErrorMessage = "Por favor, digite o nome do proprietário!")]
        [DisplayName("Proprietário")]
        public string OwnerName { get; set; }

        [Required(ErrorMessage = "Por favor, digite o CPF do proprietário!")]
        [DisplayName("CPF Proprietário")]
        [RegexReplace(ReplaceThis = ".-", WithThis = "")]
        public string OwnerCpf { get; set; }
        
    }
}

GaraceConcept/ViewModels/Vehicles/ListVehicleViewModel.cs
using GarageConcept.Models;
using System;

namespace GarageConcept.ViewModels.Vehicles
{
    public class ListVehicleViewModel
    {
        public int Id { get; internal set; }
        public DateTime Register { get; internal set; }
        public string RegisterDisplay { get; internal set; }
        public string PlateNumber { get; internal set; }
        public string ChassisNumber { get; internal set; }
        public string Model { get; internal set; }
        public string OwnerName { get; internal set; }
        public string OwnerCpf { get; internal set; }
        public string OwnerEmail { get; internal set; }
        public int OSCount { get; internal set; }

        public void Format()
        {
            this.RegisterDisplay = this.Register.ToString("dd/MM/yyyy HH:mm");
        }

    }
}

GaraceConcept/Controllers/VehiclesController.cs
using GarageConcept.Data.Context;
using GarageConcept.Models;
using GarageConcept.ViewModels.Vehicles;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace GarageConcept.Controllers
{
    [Authorize(Roles = "ADMIN")]
    public class VehiclesController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<ActionResult> Edit(int id)
        {
            using (var db = new GarageConceptContext())
            {
                var model = await db.Vehicles.Where(o => o.Id == id)
                    .Select(o => new EditVehiclesViewModel
                    {
                        Id = o.Id,
                        PlateNumber = o.PlateNumber,
                        Chassis = o.ChassisNumber,
                        OwnerCpf = o.Owner.Cpf,
                        OwnerName = o.Owner.Name,
                        VehicleModel = o.Model
                    })
                    .FirstOrDefaultAsync();
                return View(model);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(EditVehiclesViewModel model)
        {
            if (ModelState.IsValid)
            {
                using (var db = new GarageConceptContext())
                {
                    bool exists = await db.Vehicles.Where(v => v.PlateNumber == model.PlateNumber && v.Id != model.Id).AnyAsync();
                    if (exists)
                    {
                        ModelState.AddModelError(string.Empty, "Já existe um veículo cadastrado com essa placa.");
                        return View(model);
                    }
                    exists = await db.Vehicles.Where(v => v.ChassisNumber == model.Chassis && v.Id != model.Id).AnyAsync();
                    if (exists)
                    {
                        ModelState.AddModelError(string.Empty, "Já existe um veículo cadastrado com esse chassi.");
                        return View(model);
                    }
                    var vehicle = await db.Vehicles.Include(o => o.Owner).FirstOrDefaultAsync(o => o.Id == model.Id);
                    vehicle.PlateNumber = model.PlateNumber;
                    vehicle.ChassisNumber = model.Chassis;
                    vehicle.Model = model.VehicleModel;
                    if (vehicle.Owner.Cpf != model.OwnerCpf)
                    {
                        var owner = await db.Users.FirstOrDefaultAsync(u => u.Cpf == model.OwnerCpf) ?? new User(model.OwnerCpf);
                        owner.Name = model.OwnerName;
                        vehicle.Owner = owner;
                    }
                    await db.SaveChangesAsync();
                }
                return RedirectToAction("Index");
            }
            return View(model);
        }

    }
}

GaraceConcept/Views/Vehicles/Edit.cshtml
@model GarageConcept.ViewModels.Vehicles.EditVehiclesViewModel

@{
    ViewBag.Title = "Editar Veículo";
}

<div id="urls"
     data-user-details-url="@Url.HttpRouteUrl("Users.GetDetails", new { cpf = "99999999999" })"
></div>

<div class="row border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Editar Veículo @Model.Id.ToString()</h2>
        <ol class="breadcrumb">
            <li>
                <a href="@Url.Action("Index")">Listar Veículos</a>
            </li>
            <li class="active">
                <strong>Editar Veículos</strong>
            </li>
        </ol>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading"></div>
    <div class="panel-body">
        @using (Html.BeginForm("Edit", "Vehicles", FormMethod.Post, htmlAttributes: new { @class = "form-horizontal" }))
        {

            @Html.AntiForgeryToken()
            @Html.HiddenFor(o => o.Id)

            <fieldset>
                <legend>Preencha os dados abaixo</legend>
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            </fieldset>

            <div class="form-group">
                @Html.LabelFor(model => model.PlateNumber, htmlAttributes: new { @class = "control-label col-sm-2 col-md-2" })
                <div class="col-sm-6 col-md-4">
                    @Html.EditorFor(model => model.PlateNumber, new { htmlAttributes = new { @class = "form-control form-control-rounded plate", data_masked = "", data_inputmask = "'mask': 'aaa-9999'" } })
                    @Html.ValidationMessageFor(model => model.PlateNumber, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Chassis, htmlAttributes: new { @class = "control-label col-sm-2 col-md-2" })
                <div class="col-sm-6 col-md-4">
                    @Html.EditorFor(model => model.Chassis, new { htmlAttributes = new { @class = "form-control form-control-rounded", maxlength = 17 } })
                    @Html.ValidationMessageFor(model => model.Chassis, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.VehicleModel, htmlAttributes: new { @class = "control-label col-sm-2 col-md-2" })
                <div class="col-sm-6 col-md-4">
                    @Html.EditorFor(model => model.VehicleModel, new { htmlAttributes = new { @class = "form-control form-control-rounded" } })
                    @Html.ValidationMessageFor(model => model.VehicleModel, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.OwnerCpf, htmlAttributes: new { @class = "control-label col-sm-2 col-md-2" })
                <div class="col-sm-6 col-md-4">
                    @Html.EditorFor(model => model.OwnerCpf, new { htmlAttributes = new { @class = "form-control form-control-rounded cpf", data_masked = "", data_inputmask = "'mask': '999.999.999-99'" } })
                    @Html.ValidationMessageFor(model => model.OwnerCpf, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.OwnerName, htmlAttributes: new { @class = "control-label col-sm-2 col-md-2" })
                <div class="col-sm-6 col-md-4">
                    @Html.EditorFor(model => model.OwnerName, new { htmlAttributes = new { @class = "form-control form-control-rounded" } })
                    @Html.ValidationMessageFor(model => model.OwnerName, "", new { @class = "text-danger" })
                </div>
            </div>
            
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Editar" class="btn btn-success" />
                    @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-default" })
                </div>
            </div>
        }
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/inputmask")
    <script src="~/Scripts/app/vehicles/edit.js"></script>
}

GaraceConcept/Views/Vehicles/Index.cshtml
@{
    ViewBag.Title = "Veículos";
}

<div class="content-heading">
    Veículos
    <small>Listagem de Veículos Cadastrados</small>
</div>

<div class="row pt-sm pt-lg">
    <div class="col-xs-12">
        <table data-column-selection="false" id="grid-vehicles" data-get-url="@Url.HttpRouteUrl("Vehicles.Get", new { })" data-delete-url="@Url.HttpRouteUrl("Vehicles.Delete", new { id = 0 })" data-edit-url="@Url.Action("Edit", new { Id = 0 })" class="table table-condensed table-hover table-striped">
            <thead>
                <tr>
                    <th data-header-css-class="col-xs-2" data-identifier="true" data-column-id="Id">Id</th>
                    <th data-header-css-class="col-xs-3" data-column-id="PlateNumber" data-formatter="vehicle">Veículo</th>
                    <th data-header-css-class="col-xs-3" data-column-id="Owner" data-formatter="owner">Proprietário</th>
                    <th data-header-css-class="col-xs-2" data-column-id="OSCount">Qtd. OS</th>
                    <th data-header-css-class="col-xs-2" data-column-id="commands" data-formatter="commands"></th>
                </tr>
            </thead>
        </table>
    </div>
</div>


@section Styles {
    @Styles.Render("~/css/bootgrid")
}

@section Scripts
{
    @Scripts.Render("~/bundles/inputmask")
    @Scripts.Render("~/bundles/bootgrid")
    @Scripts.Render("~/bundles/bootgrid-fa")
    @Scripts.Render("~/bundles/pages/vehicles/index")
}